/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActivitiesIndexRouteImport } from './routes/activities/index'
import { Route as ActivitiesNewRouteImport } from './routes/activities/new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivitiesIndexRoute = ActivitiesIndexRouteImport.update({
  id: '/activities/',
  path: '/activities/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivitiesNewRoute = ActivitiesNewRouteImport.update({
  id: '/activities/new',
  path: '/activities/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activities/new': typeof ActivitiesNewRoute
  '/activities/': typeof ActivitiesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activities/new': typeof ActivitiesNewRoute
  '/activities': typeof ActivitiesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activities/new': typeof ActivitiesNewRoute
  '/activities/': typeof ActivitiesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/activities/new' | '/activities/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/activities/new' | '/activities'
  id: '__root__' | '/' | '/activities/new' | '/activities/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivitiesNewRoute: typeof ActivitiesNewRoute
  ActivitiesIndexRoute: typeof ActivitiesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activities/': {
      id: '/activities/'
      path: '/activities'
      fullPath: '/activities/'
      preLoaderRoute: typeof ActivitiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activities/new': {
      id: '/activities/new'
      path: '/activities/new'
      fullPath: '/activities/new'
      preLoaderRoute: typeof ActivitiesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivitiesNewRoute: ActivitiesNewRoute,
  ActivitiesIndexRoute: ActivitiesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
